name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-and-build:
    name: Check and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Use node 24
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Use bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.x.x'

      - name: Install packages
        run: bun install --frozen-lockfile

      # --prod currently does not work on workspaces :|
      # - name: Check audit
      #   run: bun audit --prod --ignore GHSA-5c6j-r48x-rmvq --ignore GHSA-qj8w-gfj5-8c6v --ignore GHSA-92pp-h63x-v22m

      - name: Build
        run: bunx turbo run build --continue=dependencies-successful
        if: ${{ success() || failure() }}

      - name: Check linter
        run: bunx turbo run check lint --continue=always
        if: ${{ success() || failure() }}

  docker:
    name: Docker image build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - ledefault
          - nas-auth
          - nas-fs
          - nas-persistance
          - nas-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Checkout actions
        uses: actions/checkout@v7
        with:
          repository: melchor629/actions
          ref: main
          token: ${{ secrets.PAT_GITHUB }}
          path: ./.github/actions
          fetch-depth: 0

      - name: Setup docker
        uses: ./.github/actions/docker/prepare

      - name: Build image
        uses: ./.github/actions/docker/build
        with:
          file: ./apps/${{ matrix.image }}/docker/Dockerfile
